import { db } from "@/db";
import { account_status, cryptos, currency } from "@/db/schema";

export async function seed() {
  // Seed account_status
  await db.insert(account_status).values([
    { id: 1, status_text: "Active", status_notice: "1" },
    { id: 2, status_text: "Not Active", status_notice: null },
    { id: 3, status_text: "Dormant", status_notice: null },
    { id: 4, status_text: "Under investigation", status_notice: null },
    { id: 5, status_text: "Needs Verification", status_notice: null },
    { id: 6, status_text: "Uploaded Document", status_notice: null },
    { id: 7, status_text: "Suspended", status_notice: null },
    { id: 8, status_text: "Low Trading Signal", status_notice: null },
    { id: 9, status_text: "Needs Account upgrade", status_notice: "null" },
    { id: 10, status_text: "Node-imbalance, fix!", status_notice: "null" },
    {
      id: 11,
      status_text: "Insufficient liquidity-backup",
      status_notice: null,
    },
  ]);

  // Seed currency
  await db.insert(currency).values([
    { id: 1, name: "US Dollar", code: "USD", comment: "", symbol: "$" },
    { id: 2, name: "Australian Dollar", code: "AUD", comment: "", symbol: "$" },
    { id: 3, name: "Brazilian Real", code: "BRL", comment: "", symbol: "R$" },
    { id: 4, name: "Canadian Dollar", code: "CAD", comment: "", symbol: "$" },
    { id: 5, name: "Czech Koruna", code: "CZK", comment: "", symbol: "CZK" },
    { id: 6, name: "Danish Krone", code: "DKK", comment: "", symbol: "Kr." },
    { id: 7, name: "Euro", code: "EUR", comment: "", symbol: "€" },
    { id: 8, name: "Thai Baht", code: "THB", comment: "", symbol: "THB" },
    {
      id: 9,
      name: "Hong Kong Dollar",
      code: "HKD",
      comment: "",
      symbol: "HL$",
    },
    {
      id: 10,
      name: "Hungarian Forint",
      code: "HUF",
      comment: "",
      symbol: "HUF",
    },
    {
      id: 11,
      name: "Israeli New Sheqel",
      code: "ILS",
      comment: "",
      symbol: "ILS",
    },
    { id: 12, name: "Japanese Yen", code: "JPY", comment: "", symbol: "JPY" },
    {
      id: 13,
      name: "Malaysian Ringgit",
      code: "MYR",
      comment: "",
      symbol: "MYR",
    },
    { id: 14, name: "Mexican Peso", code: "MXN", comment: "", symbol: "MXN" },
    { id: 15, name: "Nigeria Naira", code: "NGN", comment: "", symbol: "NGN" },
    {
      id: 16,
      name: "New Zealand Dollar",
      code: "NZD",
      comment: "",
      symbol: "$",
    },
    {
      id: 17,
      name: "Philippine Peso",
      code: "PHP",
      comment: "",
      symbol: "PHP",
    },
    { id: 18, name: "Polish Zloty ", code: "PLN", comment: "", symbol: "Z" },
    { id: 19, name: "Pound Sterling", code: "GBP", comment: "", symbol: "GBP" },
    { id: 20, name: "Russian Ruble", code: "RUB", comment: "", symbol: "RUB" },
    { id: 21, name: "Singapore Dollar", code: "SGD", comment: "", symbol: "$" },
    { id: 22, name: "Swedish Krona", code: "SEK", comment: "", symbol: "SEK" },
    { id: 23, name: "Swiss Franc", code: "CHF", comment: "", symbol: "CHF" },
    {
      id: 24,
      name: "Taiwan New Dollar",
      code: "TWD",
      comment: "",
      symbol: "$",
    },
    { id: 26, name: "Turkish Lira", code: "TRY", comment: "", symbol: "TRY" },
  ]);

  // Seed cryptos (full list)
  await db.insert(cryptos).values([
    {
      id: 1,
      coin_rank: 1,
      coin_name: "Bitcoin",
      coin_symbol: "BTC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btc.png",
      coin_id: "btc-bitcoin",
      coin_type: "coin",
      coin_color: "#fa9e32",
      coin_address: "btc address",
    },
    {
      id: 2,
      coin_rank: 2,
      coin_name: "Ethereum",
      coin_symbol: "ETH",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eth.png",
      coin_id: "eth-ethereum",
      coin_type: "coin",
      coin_color: "#282a2a",
      coin_address: "Ether address",
    },
    {
      id: 3,
      coin_rank: 3,
      coin_name: "Tether",
      coin_symbol: "USDT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdt.png",
      coin_id: "usdt-tether",
      coin_type: "token",
      coin_color: "#24a37c",
      coin_address: "usdt address",
    },
    {
      id: 4,
      coin_rank: 4,
      coin_name: "Binance Coin",
      coin_symbol: "BNB",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bnb.png",
      coin_id: "bnb-binance-coin",
      coin_type: "coin",
      coin_color: "#f4bc2c",
      coin_address: null,
    },
    {
      id: 5,
      coin_rank: 5,
      coin_name: "USD Coin",
      coin_symbol: "USDC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdc.png",
      coin_id: "usdc-usd-coin",
      coin_type: "token",
      coin_color: "#eef4f9",
      coin_address: null,
    },
    {
      id: 6,
      coin_rank: 6,
      coin_name: "XRP",
      coin_symbol: "XRP",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrp.png",
      coin_id: "xrp-xrp",
      coin_type: "coin",
      coin_color: "#040404",
      coin_address: null,
    },
    {
      id: 7,
      coin_rank: 7,
      coin_name: "Terra",
      coin_symbol: "LUNA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/luna.png",
      coin_id: "luna-terra",
      coin_type: "coin",
      coin_color: "#f3cf3a",
      coin_address: null,
    },
    {
      id: 9,
      coin_rank: 9,
      coin_name: "Cardano",
      coin_symbol: "ADA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ada.png",
      coin_id: "ada-cardano",
      coin_type: "coin",
      coin_color: "#226ed8",
      coin_address: null,
    },
    {
      id: 10,
      coin_rank: 10,
      coin_name: "Solana",
      coin_symbol: "SOL",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sol.png",
      coin_id: "sol-solana",
      coin_type: "token",
      coin_color: "#68a1c9",
      coin_address: null,
    },
  ]);

  await db.insert(cryptos).values([
    {
      id: 11,
      coin_rank: 11,
      coin_name: "Avalanche",
      coin_symbol: "AVAX",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/avax.png",
      coin_id: "avax-avalanche",
      coin_type: "coin",
      coin_color: "#eb4343",
      coin_address: null,
    },
    {
      id: 12,
      coin_rank: 12,
      coin_name: "Binance USD",
      coin_symbol: "BUSD",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/busd.png",
      coin_id: "busd-binance-usd",
      coin_type: "token",
      coin_color: "#f4bc0c",
      coin_address: null,
    },
    {
      id: 13,
      coin_rank: 13,
      coin_name: "Polkadot",
      coin_symbol: "DOT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dot.png",
      coin_id: "dot-polkadot",
      coin_type: "coin",
      coin_color: "#e4047c",
      coin_address: null,
    },
    {
      id: 14,
      coin_rank: 14,
      coin_name: "Dogecoin",
      coin_symbol: "DOGE",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/doge.png",
      coin_id: "doge-dogecoin",
      coin_type: "coin",
      coin_color: "#eee0b6",
      coin_address: null,
    },
    {
      id: 15,
      coin_rank: 15,
      coin_name: "TerraUSD",
      coin_symbol: "UST",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ust.png",
      coin_id: "ust-terrausd",
      coin_type: "token",
      coin_color: "#e28a8b",
      coin_address: null,
    },
    {
      id: 16,
      coin_rank: 16,
      coin_name: "Wrapped Bitcoin",
      coin_symbol: "WBTC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbtc.png",
      coin_id: "wbtc-wrapped-bitcoin",
      coin_type: "token",
      coin_color: "#f09444",
      coin_address: null,
    },
    {
      id: 17,
      coin_rank: 17,
      coin_name: "Polygon",
      coin_symbol: "MATIC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/matic.png",
      coin_id: "matic-polygon",
      coin_type: "coin",
      coin_color: "#8444e4",
      coin_address: null,
    },
    {
      id: 18,
      coin_rank: 18,
      coin_name: "Shiba Inu",
      coin_symbol: "SHIB",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/shib.png",
      coin_id: "shib-shiba-inu",
      coin_type: "token",
      coin_color: "#faa00d",
      coin_address: null,
    },
    {
      id: 19,
      coin_rank: 19,
      coin_name: "Litecoin",
      coin_symbol: "LTC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ltc.png",
      coin_id: "ltc-litecoin",
      coin_type: "coin",
      coin_color: "#345c9c",
      coin_address: null,
    },
    {
      id: 21,
      coin_rank: 21,
      coin_name: "Cosmos",
      coin_symbol: "ATOM",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/atom.png",
      coin_id: "atom-cosmos",
      coin_type: "coin",
      coin_color: "#30334c",
      coin_address: null,
    },
    {
      id: 23,
      coin_rank: 23,
      coin_name: "Bitcoin Cash",
      coin_symbol: "BCH",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bch.png",
      coin_id: "bch-bitcoin-cash",
      coin_type: "coin",
      coin_color: "#f1f9f7",
      coin_address: null,
    },
    {
      id: 25,
      coin_rank: 25,
      coin_name: "Dai",
      coin_symbol: "DAI",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dai.png",
      coin_id: "dai-dai",
      coin_type: "token",
      coin_color: "#fcb934",
      coin_address: null,
    },
    {
      id: 26,
      coin_rank: 26,
      coin_name: "TRON",
      coin_symbol: "TRX",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/trx.png",
      coin_id: "trx-tron",
      coin_type: "coin",
      coin_color: "#c43429",
      coin_address: null,
    },
    {
      id: 27,
      coin_rank: 27,
      coin_name: "FTX Token",
      coin_symbol: "FTT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ftt.png",
      coin_id: "ftt-ftx-token",
      coin_type: "token",
      coin_color: "#5cccdc",
      coin_address: null,
    },
    {
      id: 28,
      coin_rank: 28,
      coin_name: "Ethereum Classic",
      coin_symbol: "ETC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/etc.png",
      coin_id: "etc-ethereum-classic",
      coin_type: "coin",
      coin_color: "#3ab93a",
      coin_address: null,
    },
    {
      id: 30,
      coin_rank: 30,
      coin_name: "Chainlink",
      coin_symbol: "LINK",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/link.png",
      coin_id: "link-chainlink",
      coin_type: "token",
      coin_color: "#2959d9",
      coin_address: null,
    },
    {
      id: 31,
      coin_rank: 31,
      coin_name: "Uniswap",
      coin_symbol: "UNI",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/uni.png",
      coin_id: "uni-uniswap",
      coin_type: "token",
      coin_color: "#fc047c",
      coin_address: null,
    },
    {
      id: 32,
      coin_rank: 32,
      coin_name: "OKB",
      coin_symbol: "OKB",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/okb.png",
      coin_id: "okb-okb",
      coin_type: "token",
      coin_color: "#3974ee",
      coin_address: null,
    },
    {
      id: 33,
      coin_rank: 33,
      coin_name: "Algorand",
      coin_symbol: "ALGO",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/algo.png",
      coin_id: "algo-algorand",
      coin_type: "coin",
      coin_color: "#efefef",
      coin_address: null,
    },
    {
      id: 34,
      coin_rank: 34,
      coin_name: "Stellar",
      coin_symbol: "XLM",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xlm.png",
      coin_id: "xlm-stellar",
      coin_type: "coin",
      coin_color: "#040404",
      coin_address: null,
    },
  ]);

  await db.insert(cryptos).values([
    {
      id: 35,
      coin_rank: 35,
      coin_name: "Decentraland",
      coin_symbol: "MANA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mana.png",
      coin_id: "mana-decentraland",
      coin_type: "token",
      coin_color: "#f64e5c",
      coin_address: null,
    },
    {
      id: 36,
      coin_rank: 36,
      coin_name: "Hedera Hashgraph",
      coin_symbol: "HBAR",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/hbar.png",
      coin_id: "hbar-hedera-hashgraph",
      coin_type: "coin",
      coin_color: "#f8f8f8",
      coin_address: null,
    },
    {
      id: 37,
      coin_rank: 37,
      coin_name: "Elrond",
      coin_symbol: "EGLD",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/egld.png",
      coin_id: "egld-elrond",
      coin_type: "coin",
      coin_color: "#060606",
      coin_address: null,
    },
    {
      id: 38,
      coin_rank: 38,
      coin_name: "Internet Computer",
      coin_symbol: "ICP",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/icp.png",
      coin_id: "icp-internet-computer",
      coin_type: "coin",
      coin_color: "#ea594e",
      coin_address: null,
    },
    {
      id: 39,
      coin_rank: 39,
      coin_name: "The Sandbox",
      coin_symbol: "SAND",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sand.png",
      coin_id: "sand-the-sandbox",
      coin_type: "token",
      coin_color: "#f3f9fb",
      coin_address: null,
    },
    {
      id: 40,
      coin_rank: 40,
      coin_name: "Monero",
      coin_symbol: "XMR",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xmr.png",
      coin_id: "xmr-monero",
      coin_type: "coin",
      coin_color: "#fc6404",
      coin_address: null,
    },
    {
      id: 41,
      coin_rank: 41,
      coin_name: "Waves",
      coin_symbol: "WAVES",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/waves.png",
      coin_id: "waves-waves",
      coin_type: "coin",
      coin_color: "#36b3d5",
      coin_address: null,
    },
    {
      id: 42,
      coin_rank: 42,
      coin_name: "VeChain",
      coin_symbol: "VET",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/vet.png",
      coin_id: "vet-vechain",
      coin_type: "coin",
      coin_color: "#6488e1",
      coin_address: null,
    },
    {
      id: 43,
      coin_rank: 43,
      coin_name: "Filecoin",
      coin_symbol: "FIL",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fil.png",
      coin_id: "fil-filecoin",
      coin_type: "coin",
      coin_color: "#0492fc",
      coin_address: null,
    },
    {
      id: 44,
      coin_rank: 44,
      coin_name: "Fantom",
      coin_symbol: "FTM",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ftm.png",
      coin_id: "ftm-fantom",
      coin_type: "coin",
      coin_color: "#e4e4e4",
      coin_address: null,
    },
    {
      id: 45,
      coin_rank: 45,
      coin_name: "Axie Infinity",
      coin_symbol: "AXS",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/axs.png",
      coin_id: "axs-axie-infinity",
      coin_type: "token",
      coin_color: "#0f48b3",
      coin_address: null,
    },
    {
      id: 49,
      coin_rank: 49,
      coin_name: "Tezos",
      coin_symbol: "XTZ",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xtz.png",
      coin_id: "xtz-tezos",
      coin_type: "coin",
      coin_color: "#2c84fc",
      coin_address: null,
    },
    {
      id: 50,
      coin_rank: 50,
      coin_name: "THORChain",
      coin_symbol: "RUNE",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rune.png",
      coin_id: "rune-thorchain",
      coin_type: "token",
      coin_color: "#34fcb4",
      coin_address: null,
    },
    {
      id: 51,
      coin_rank: 51,
      coin_name: "Helium",
      coin_symbol: "HNT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/hnt.png",
      coin_id: "hnt-helium",
      coin_type: "coin",
      coin_color: "#eaf5fa",
      coin_address: null,
    },
    {
      id: 53,
      coin_rank: 53,
      coin_name: "Zcash",
      coin_symbol: "ZEC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/zec.png",
      coin_id: "zec-zcash",
      coin_type: "coin",
      coin_color: "#e4a93d",
      coin_address: null,
    },
    {
      id: 54,
      coin_rank: 54,
      coin_name: "EOS",
      coin_symbol: "EOS",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eos.png",
      coin_id: "eos-eos",
      coin_type: "coin",
      coin_color: "#ebebeb",
      coin_address: null,
    },
    {
      id: 56,
      coin_rank: 56,
      coin_name: "Flow",
      coin_symbol: "FLOW",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/flow.png",
      coin_id: "flow-flow",
      coin_type: "coin",
      coin_color: "#f3fbf8",
      coin_address: null,
    },
    {
      id: 57,
      coin_rank: 57,
      coin_name: "IOTA",
      coin_symbol: "MIOTA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/miota.png",
      coin_id: "miota-iota",
      coin_type: "coin",
      coin_color: "#040404",
      coin_address: null,
    },
    {
      id: 58,
      coin_rank: 58,
      coin_name: "Huobi Token",
      coin_symbol: "HT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ht.png",
      coin_id: "ht-huobi-token",
      coin_type: "token",
      coin_color: "#049cdc",
      coin_address: null,
    },
    {
      id: 59,
      coin_rank: 59,
      coin_name: "Aave",
      coin_symbol: "AAVE",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/aave.png",
      coin_id: "aave-new",
      coin_type: "token",
      coin_color: "#688cb5",
      coin_address: null,
    },
    {
      id: 60,
      coin_rank: 60,
      coin_name: "Maker",
      coin_symbol: "MKR",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mkr.png",
      coin_id: "mkr-maker",
      coin_type: "token",
      coin_color: "#1cac9c",
      coin_address: null,
    },
  ]);

  await db.insert(cryptos).values([
    {
      id: 61,
      coin_rank: 61,
      coin_name: "The Graph",
      coin_symbol: "GRT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/grt.png",
      coin_id: "grt-the-graph",
      coin_type: "token",
      coin_color: "#453bab",
      coin_address: null,
    },
    {
      id: 62,
      coin_rank: 62,
      coin_name: "PancakeSwap",
      coin_symbol: "CAKE",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cake.png",
      coin_id: "cake-pancakeswap",
      coin_type: "token",
      coin_color: "#945d28",
      coin_address: null,
    },
    {
      id: 64,
      coin_rank: 64,
      coin_name: "Bitcoin SV",
      coin_symbol: "BSV",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bsv.png",
      coin_id: "bsv-bitcoin-sv",
      coin_type: "coin",
      coin_color: "#ebb304",
      coin_address: null,
    },
    {
      id: 66,
      coin_rank: 66,
      coin_name: "Stacks",
      coin_symbol: "STX",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_stx.png",
      coin_id: "stx-stacks",
      coin_type: "coin",
      coin_color: "#5546fc",
      coin_address: null,
    },
    {
      id: 68,
      coin_rank: 68,
      coin_name: "NEO",
      coin_symbol: "NEO",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/neo.png",
      coin_id: "neo-neo",
      coin_type: "coin",
      coin_color: "#81c425",
      coin_address: null,
    },
    {
      id: 69,
      coin_rank: 69,
      coin_name: "Harmony",
      coin_symbol: "ONE",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/one.png",
      coin_id: "one-harmony",
      coin_type: "coin",
      coin_color: "#35d3d3",
      coin_address: null,
    },
    {
      id: 70,
      coin_rank: 70,
      coin_name: "Gala",
      coin_symbol: "GALA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/gala.png",
      coin_id: "gala-gala",
      coin_type: "token",
      coin_color: "#040404",
      coin_address: null,
    },
    {
      id: 71,
      coin_rank: 71,
      coin_name: "eCash",
      coin_symbol: "XEC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xec.png",
      coin_id: "xec-ecash",
      coin_type: "coin",
      coin_color: "#0977c5",
      coin_address: null,
    },
    {
      id: 72,
      coin_rank: 72,
      coin_name: "Quant",
      coin_symbol: "QNT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/qnt.png",
      coin_id: "qnt-quant",
      coin_type: "token",
      coin_color: "#ec3b1b",
      coin_address: null,
    },
    {
      id: 77,
      coin_rank: 77,
      coin_name: "Dash",
      coin_symbol: "DASH",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dash.png",
      coin_id: "dash-dash",
      coin_type: "coin",
      coin_color: "#048ce4",
      coin_address: null,
    },
    {
      id: 78,
      coin_rank: 78,
      coin_name: "Kusama",
      coin_symbol: "KSM",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ksm.png",
      coin_id: "ksm-kusama",
      coin_type: "coin",
      coin_color: "#040404",
      coin_address: null,
    },
    {
      id: 79,
      coin_rank: 79,
      coin_name: "Enjin Coin",
      coin_symbol: "ENJ",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/enj.png",
      coin_id: "enj-enjin-coin",
      coin_type: "token",
      coin_color: "#3cdef7",
      coin_address: null,
    },
    {
      id: 81,
      coin_rank: 81,
      coin_name: "Nexo",
      coin_symbol: "NEXO",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/nexo.png",
      coin_id: "nexo-nexo",
      coin_type: "token",
      coin_color: "#bdd7e9",
      coin_address: null,
    },
    {
      id: 82,
      coin_rank: 82,
      coin_name: "Basic Attention Token",
      coin_symbol: "BAT",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bat.png",
      coin_id: "bat-basic-attention-token",
      coin_type: "token",
      coin_color: "#86297c",
      coin_address: null,
    },
    {
      id: 83,
      coin_rank: 83,
      coin_name: "Convex Finance",
      coin_symbol: "CVX",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cvx.png",
      coin_id: "cvx-convex-finance",
      coin_type: "token",
      coin_color: "#3c474c",
      coin_address: null,
    },
    {
      id: 84,
      coin_rank: 84,
      coin_name: "Loopring",
      coin_symbol: "LRC",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lrc.png",
      coin_id: "lrc-loopring",
      coin_type: "token",
      coin_color: "#040404",
      coin_address: null,
    },
    {
      id: 85,
      coin_rank: 85,
      coin_name: "Arweave",
      coin_symbol: "AR",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ar.png",
      coin_id: "ar-arweave",
      coin_type: "token",
      coin_color: "#242424",
      coin_address: null,
    },
    {
      id: 86,
      coin_rank: 86,
      coin_name: "Curve DAO Token",
      coin_symbol: "CRV",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/crv.png",
      coin_id: "crv-curve-dao-token",
      coin_type: "token",
      coin_color: "#d3e226",
      coin_address: null,
    },
    {
      id: 87,
      coin_rank: 87,
      coin_name: "Kadena",
      coin_symbol: "KDA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kda.png",
      coin_id: "kda-kadena",
      coin_type: "coin",
      coin_color: "#c445b0",
      coin_address: null,
    },
    {
      id: 88,
      coin_rank: 88,
      coin_name: "Chiliz",
      coin_symbol: "CHZ",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/chz.png",
      coin_id: "chz-chiliz",
      coin_type: "token",
      coin_color: "#cc0524",
      coin_address: null,
    },
    {
      id: 92,
      coin_rank: 92,
      coin_name: "Mina Protocol",
      coin_symbol: "MINA",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mina.png",
      coin_id: "mina-mina-protocol",
      coin_type: "coin",
      coin_color: "#bf91b1",
      coin_address: null,
    },
    {
      id: 94,
      coin_rank: 94,
      coin_name: "Theta Fuel",
      coin_symbol: "TFUEL",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/tfuel.png",
      coin_id: "tfuel-theta-fuel",
      coin_type: "coin",
      coin_color: "#fc8212",
      coin_address: null,
    },
    {
      id: 95,
      coin_rank: 95,
      coin_name: "IoTeX",
      coin_symbol: "IOTX",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/iotx.png",
      coin_id: "iotx-iotex",
      coin_type: "token",
      coin_color: "#04d4c3",
      coin_address: null,
    },
    {
      id: 96,
      coin_rank: 96,
      coin_name: "Oasis Network",
      coin_symbol: "ROSE",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rose.png",
      coin_id: "rose-oasis-network",
      coin_type: "token",
      coin_color: "#0493f5",
      coin_address: null,
    },
    {
      id: 97,
      coin_rank: 97,
      coin_name: "Decred",
      coin_symbol: "DCR",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dcr.png",
      coin_id: "dcr-decred",
      coin_type: "coin",
      coin_color: "#277cee",
      coin_address: null,
    },
    {
      id: 99,
      coin_rank: 99,
      coin_name: "Bitcoin Gold",
      coin_symbol: "BTG",
      coin_logo:
        "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btg.png",
      coin_id: "btg-bitcoin-gold",
      coin_type: "coin",
      coin_color: "#173074",
      coin_address: null,
    },
  ]);

  return "✅ Database seed completed.";
}
